name = "Hugo Private pages"
license = "MIT"
licenselink = "https://github.com/notmarrco/hugo-privatepages/blob/master/LICENSE"
description = "Modify default sitemap.xml and rss to hide specified pages."
homepage = "https://github.com/notmarrco/hugo-privatepages"
tags = ["privacy"]
features = []
min_version = "0.41.0"

[author]
  name = "notmarrco"
  homepage = "https://github.com/notmarrco"
